name: latte1
channels:
  - pytorch
  - nvidia
dependencies:
  - python==3.10
  - pip:
    - timm
    - diffusers[torch]==0.24.0
    - accelerate
    - tensorboard
    - einops
    - transformers
    - av
    - scikit-image
    - decord
    - pandas
    - imageio-ffmpeg
