# dataset
dataset: "ffs"
data_path: "/media/hdd/yfliu/datasets/preprocess_ffs/train/videos"
data_path: /home/extradisk/liuyaofang/datasets/sky_timelapse/sky_train
pretrained_model_path: /home/extradisk/liuyaofang/model_zoo/Latte
# save and load
results_dir: "/media/hdd/yfliu/Latte_backup/results_noise_video"
# pretrained: 
# pretrained: /media/hdd/yfliu/Latte_backup/results_noise_video/2024-08-12_00-41-24/000-LatteVIDEO-B-2-F16S3-ffs/checkpoints/0120000.pt
pretrained: /home/extradisk/liuyaofang/Latte/results_noise_video/0150000.pt
# model config: 
# model: Latte-XL/2
model: LatteVIDEO-B/2
video_length: 16
num_frames: 16
image_size: 256 # choices=[256, 512]
num_sampling_steps: 250
# num_sampling_steps: 50
frame_interval: 3
# frame_interval: 1
fixed_spatial: False
attention_bias: True
learn_sigma: True # important
extras: 1 # [1, 2] 1 unconditional generation, 2 class-conditional generation

#TODO Use less configs!!!!
learn_sigma_noise: False
# condition_noise: True # whether condition on noiser or not
condition_noise: False
# new for model_noise
max_period: 3

# train config:
save_ceph: True # important
learning_rate: 1e-4
ckpt_every: 10000
clip_max_norm: 0.1
start_clip_iter: 500000
# local_batch_size: 5 # important
local_batch_size: 3 # important
max_train_steps: 300002
global_seed: 3407
num_workers: 8
log_every: 50
lr_warmup_steps: 0
resume_from_checkpoint:
gradient_accumulation_steps: 1 # TODO
num_classes:

# low VRAM and speed up training
use_compile: False
mixed_precision: False
enable_xformers_memory_efficient_attention: False
gradient_checkpointing: False